const env = () => `NODE_ENV=development
USER=
PORT=
DATABASE= 
DATABASE_LOCAL= mongodb://localhost:27017/
DATABASE_PASSWORD=
SQL_DB_DIALECT=
SQL_DB_HOST=
SQL_DB_PORT=
SQL_DB_NAME=
SQL_DB_USER=
SQL_DB_PASSWORD=
`;

export default env;
